import { describe, expect, test } from "bun:test"
import { inlineCodeKind, stripInlineCodeLocation } from "./markdown-inline-code-kind"

describe("inlineCodeKind", () => {
  test("leaves code expressions and non-file slash tokens as normal inline code", () => {
    expect(
      inlineCodeKind(`case "form.created": ... input.setStore("form", form.sessionID, [form]) / splice/insert`),
    ).toBeUndefined()
    expect(inlineCodeKind(`<SessionQuestionDock request={request} ... />`)).toBeUndefined()
    expect(inlineCodeKind(`from sync.data.form + sync.data.session.`)).toBeUndefined()
    expect(inlineCodeKind(`@opencode/app <StatusPopover />)`)).toBeUndefined()
    expect(inlineCodeKind(`sync.data.session`)).toBeUndefined()
    expect(inlineCodeKind(`window.api`)).toBeUndefined()
    expect(inlineCodeKind(`props.id`)).toBeUndefined()
    expect(inlineCodeKind(`event.target`)).toBeUndefined()
    expect(inlineCodeKind(`item.tool`)).toBeUndefined()
    expect(inlineCodeKind(`req.url`)).toBeUndefined()
    expect(inlineCodeKind(`process.env`)).toBeUndefined()
    expect(inlineCodeKind(`console.log`)).toBeUndefined()
    expect(inlineCodeKind(`logger.log`)).toBeUndefined()
    expect(inlineCodeKind(`Object.is`)).toBeUndefined()
    expect(inlineCodeKind(`obj.x`)).toBeUndefined()
    expect(inlineCodeKind(`obj.c`)).toBeUndefined()
    expect(inlineCodeKind(`this.props`)).toBeUndefined()
    expect(inlineCodeKind(`res.json`)).toBeUndefined()
    expect(inlineCodeKind(`s.lock`)).toBeUndefined()
    expect(inlineCodeKind(`config.mod`)).toBeUndefined()
    expect(inlineCodeKind(`el.flex`)).toBeUndefined()
    expect(inlineCodeKind(`x.pub`)).toBeUndefined()
    expect(inlineCodeKind(`example.com/foo.js`)).toBeUndefined()
    expect(inlineCodeKind(`localhost:3000/app.js`)).toBeUndefined()
    expect(inlineCodeKind(`workspace`)).toBeUndefined()
    expect(inlineCodeKind(`root`)).toBeUndefined()
    expect(inlineCodeKind(`build`)).toBeUndefined()
    expect(inlineCodeKind(`readme`)).toBeUndefined()
    expect(inlineCodeKind(`license`)).toBeUndefined()
    expect(inlineCodeKind(`true/false`)).toBeUndefined()
    expect(inlineCodeKind(`read/write`)).toBeUndefined()
    expect(inlineCodeKind(`application/json`)).toBeUndefined()
    expect(inlineCodeKind(`origin/v2`)).toBeUndefined()
    expect(inlineCodeKind(`@opencode/app`)).toBeUndefined()
    expect(inlineCodeKind(`session/status`)).toBeUndefined()
    expect(inlineCodeKind(`anthropic/claude-sonnet-4`)).toBeUndefined()
    expect(inlineCodeKind(`CI/CD`)).toBeUndefined()
    expect(inlineCodeKind(`1.2`)).toBeUndefined()
  })

  test("detects file paths, anchored paths, and line-suffixed references", () => {
    expect(inlineCodeKind(`app.tsx`)).toBe("path")
    expect(inlineCodeKind(`session.ts`)).toBe("path")
    expect(inlineCodeKind(`context.ts`)).toBe("path")
    expect(inlineCodeKind(`store.ts`)).toBe("path")
    expect(inlineCodeKind(`state.tsx`)).toBe("path")
    expect(inlineCodeKind(`options.ts`)).toBe("path")
    expect(inlineCodeKind(`event.ts`)).toBe("path")
    expect(inlineCodeKind(`a.ts`)).toBe("path")
    expect(inlineCodeKind(`app.tsx:42`)).toBe("path")
    expect(inlineCodeKind(`app.tsx:42:10`)).toBe("path")
    expect(inlineCodeKind(`app.tsx#L42-L55`)).toBe("path")
    expect(inlineCodeKind(`vite.config.mjs`)).toBe("path")
    expect(inlineCodeKind(`eslint.config.cjs`)).toBe("path")
    expect(inlineCodeKind(`app.d.ts`)).toBe("path")
    expect(inlineCodeKind(`component.svelte`)).toBe("path")
    expect(inlineCodeKind(`schema.graphql`)).toBe("path")
    expect(inlineCodeKind(`Dockerfile`)).toBe("path")
    expect(inlineCodeKind(`Dockerfile.dev`)).toBe("path")
    expect(inlineCodeKind(`README`)).toBe("path")
    expect(inlineCodeKind(`LICENSE`)).toBe("path")
    expect(inlineCodeKind(`CHANGELOG`)).toBe("path")
    expect(inlineCodeKind(`main.c`)).toBe("path")
    expect(inlineCodeKind(`foo.h`)).toBe("path")
    expect(inlineCodeKind(`logs/server.log`)).toBe("path")
    expect(inlineCodeKind(`demo.gif`)).toBe("path")
    expect(inlineCodeKind(`.gitignore`)).toBe("path")
    expect(inlineCodeKind(`.env.local`)).toBe("path")
    expect(inlineCodeKind(`Cargo.lock`)).toBe("path")
    expect(inlineCodeKind(`yarn.lock`)).toBe("path")
    expect(inlineCodeKind(`go.mod`)).toBe("path")
    expect(inlineCodeKind(`go.sum`)).toBe("path")
    expect(inlineCodeKind(`bun.lockb`)).toBe("path")
    expect(inlineCodeKind(`terraform.tfvars`)).toBe("path")
    expect(inlineCodeKind(`pnpm-lock.yaml`)).toBe("path")
    expect(inlineCodeKind(`src/file.ts`)).toBe("path")
    expect(inlineCodeKind(`src/main.c:12`)).toBe("path")
    expect(inlineCodeKind(`packages/desktop-electron`)).toBe("path")
    expect(inlineCodeKind(`packages/app/src`)).toBe("path")
    expect(inlineCodeKind(`/etc/hosts`)).toBe("path")
    expect(inlineCodeKind(`/home/u/proj/src`)).toBe("path")
    expect(inlineCodeKind(`@opencode/session-ui/src/components/markdown.tsx`)).toBe("path")
    expect(inlineCodeKind(`~/.config/opencode`)).toBe("path")
    expect(inlineCodeKind(`./scripts/release`)).toBe("path")
  })

  test("detects urls", () => {
    expect(inlineCodeKind(`https://opencode.ai/docs`)).toBe("url")
    expect(inlineCodeKind(`http://localhost:4444`)).toBe("url")
    expect(inlineCodeKind(`file:///tmp/opencode`)).toBeUndefined()
    expect(inlineCodeKind(`ftp://opencode.ai/docs`)).toBeUndefined()
  })

  test("strips line and range suffixes without corrupting drive roots", () => {
    expect(stripInlineCodeLocation(`src/app.tsx:42`)).toBe(`src/app.tsx`)
    expect(stripInlineCodeLocation(`src/app.tsx:42:8`)).toBe(`src/app.tsx`)
    expect(stripInlineCodeLocation(`src/app.tsx:42-50`)).toBe(`src/app.tsx`)
    expect(stripInlineCodeLocation(`src/app.tsx#L42-L50`)).toBe(`src/app.tsx`)
    expect(stripInlineCodeLocation(`C:/tmp/file.ts:10`)).toBe(`C:/tmp/file.ts`)
  })
})
